# Generated by Django 5.0.14 on 2026-02-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=255, verbose_name="Company Name"),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                ("email", models.EmailField(max_length=254, verbose_name="Work Email")),
                ("use_case", models.CharField(max_length=255, verbose_name="Use Case")),
                (
                    "message",
                    models.TextField(blank=True, verbose_name="Additional Details"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Approved"),
                ),
            ],
            options={
                "verbose_name": "API Request",
                "verbose_name_plural": "API Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Subject"
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contact Submission",
                "verbose_name_plural": "Contact Submissions",
                "ordering": ["-created_at"],
            },
        ),
    ]
